project: https://github.com/qualcomm/fastrpc

branches:
  ayukum-test:
    modes:
      blocking:
        headers:
          - inc/remote.h
          - inc/remote64.h
          - inc/dspqueue.h
          - inc/rpcmem.h
          - inc/test.h
